AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: LF1-indexPhotos
      Handler: indexPhotos.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::533947249138:role/Role-1'
      Events:
        S3Trigger:
          Type: S3
          Properties:
            Bucket: !Ref SrcBucket
            Events: s3:ObjectCreated:*
      Environment:
        Variables:
          REGION: us-east-1
  SrcBucket:
    Type: AWS::S3::Bucket

